import { ReactNode } from 'react'
import { Prompt } from 'next/font/google'

import '@/styles/globals.css'
import { kinetica } from '@/styles/fonts'
import CursorFollower from '@/components/shared/CursorFollower'

const prompt = Prompt({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  display: 'swap',
  variable: '--font-prompt'
})

export const metadata = {
  title: 'Prestani da radiš za gazdu, nauči da prodaješ na domaćem tržištu',
  description: 'Generated by create next app',
  icons: [
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '32x32',
      url: '/favicon/favicon-32x32.png'
    },
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '16x16',
      url: '/favicon/favicon-16x16.png'
    },
    {
      rel: 'apple-touch-icon',
      sizes: '180x180',
      url: '/favicon/apple-touch-icon.png'
    }
  ]
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="sr">
      <head>
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#8000FF" />
        <meta name="msapplication-TileColor" content="#8000FF" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body className={`${prompt.variable} ${kinetica.variable} font-prompt`}>
        <CursorFollower>{children}</CursorFollower>
      </body>
    </html>
  )
}
