import { ReactNode } from 'react'
import { Prompt } from 'next/font/google'

import '@/styles/globals.css'
import { kinetica } from '@/styles/fonts'

const prompt = Prompt({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  display: 'swap',
  variable: '--font-prompt'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="sr">
      <body className={`${prompt.variable} ${kinetica.variable} font-prompt`}>
        {children}
      </body>
    </html>
  )
}
